# Generated by Django 4.0.5 on 2022-06-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='movie_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_index',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='poster',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
