# Generated by Django 4.0.5 on 2022-06-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_genre_id_movieinfo_movie_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='movieinfo',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_index',
        ),
    ]
