# Generated by Django 4.0.5 on 2022-06-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_genre_id_movieinfo_movie_id_and_more'),
        ('movies', '0003_movieinfo_idtmdb'),
    ]

    operations = [
    ]
