# Generated by Django 4.0.5 on 2022-06-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_merge_20220605_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='movieinfo',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_index',
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='ne',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
